apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-dhcp-test
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "testbr1",
      "hairpinMode": true,
      "master": "env32",
      "ipam": {
        "type": "dhcp"
      }
    }'
