apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-ipam-static
spec:
  config: '{
          "name": "macvlan-ipam-static",
          "type": "macvlan",
          "mode": "macvlan-mode",
          "master": "env32",
          "ipam": {
                    "type": "static",
                    "addresses": [
                        {
                          "address": "192.168.1.0/24",
                          "gateway": "192.168.1.1"
                        }
                    ]
          }
  }'
